### ISSUE TITLE
DROP TABLE fails on Postgres because of double escaped table names

### ISSUE THREAD

**Issue by ooktay** [micronaut-projects/micronaut-data#383]
# Task List

- [x ] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Using this config:
datasources:
  default:
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP
    dialect: POSTGRES
2. Run app twice 

### Expected Behaviour
Tables created on first run are dropped and re-created

### Actual Behaviour
DROP table fails. See LOG: io.micronaut.data.query = TRACE

17:31:43.368 [Test worker] DEBUG io.micronaut.data.query - Dropping Table: 
DROP TABLE ""project"";
17:31:43.370 [Test worker] TRACE io.micronaut.data.query - Drop Failed: ERROR: zero-length delimited identifier at or near """"
  Position: 12

### Possible solution:
table names in DROP statements are double-escaped
Remove escape code in io.micronaut.data.model.query.builder.sql.SqlQueryBuilder#buildDropTableStatements

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue
