### ISSUE TITLE
Unable to introspect imported (JAR/dependency) classes

### ISSUE THREAD

**Issue by sk8geek** [micronaut-projects/micronaut-data#596]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to GitLab
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Include a library as a dependency (or jar in my example)
2. Use `@Introspected(package..., includeAnnotations...)` to inspect the package/classes
3. Attempts to reference the domain classes result in an error `Cannot validate uk.co.channele.test.maven.domain.Student. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled`

I have included a link to examples of both the maven project used to produce the `Student` domain class and package it as a JAR file, and the Micronaut project to illustrate the issue. If I copy the `Student` class (in it's package) into the project directly and remove the `@Introspected` annotation then I can `POST` to the controller and a student record is created. The list can be retrieved via a `GET` call to the same endpoint.

### Expected Behaviour

The imported classes should be introspected and usable in a respository. A `POST` call to `http://localhost:8080/students/` should result in a `204` response. A subsequent `GET` call to the same endpoint returns a list of students.

### Actual Behaviour

In the provided example a `POST` request to `http://localhost:8080/students/` with a string as the body causes:
```
POST http://localhost:8080/students/

HTTP/1.1 400 Bad Request
Date: Mon, 15 Jun 2020 16:26:23 GMT
content-type: application/json
content-length: 258
connection: close

{
  "message": "arg0: Cannot validate uk.co.channele.test.maven.domain.Student. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled",
  "_links": {
    "self": {
      "href": "/students/",
      "templated": false
    }
  }
}

Response code: 400 (Bad Request); Time: 680ms; Content length: 258 bytes
```

### Environment Information

- **Operating System**: Fedora 32
- **Micronaut Version:** 1.3.5
- **JDK Version:** openjdk version "1.8.0_252"
also a Groovy project with:
- **Micronaut Version:** 1.3.6
- **JDK Version:** 11.0.7-open

### Example Application

- The Micronaut application: https://gitlab.com/sk8geek/test-introspection
- The Maven project: https://gitlab.com/sk8geek/test-introspection-domain-class

**Comment by graemerocher** [comment]
Does the submodule have the micronaut annotation processors enabled?

**Comment by sk8geek** [comment]
Hi, no. The Maven project is **not** a Micronaut project. The Maven project defines classes that I wish to share across multiple projects. In this case they are `@Entity` classes that define the object types in a database. Both projects use `javax.persistence` annotations. 

Following my understanding of the documentation (section 3.14 in the guide) I am trying to use `@Introspected` in the Micronaut project to introspect the "imported" classes and use them as `@Entity` objects.

thanks

**Comment by graemerocher** [comment]
PR submitted for this here https://github.com/micronaut-projects/micronaut-core/pull/4157
