### ISSUE TITLE
Pageable previous method incorrect

### ISSUE THREAD

**Issue by arichiardi** [micronaut-projects/micronaut-data#597]
Hi there, I might have found a problem with the implementation of `Pageable.previous()`.

If this is expected I apologize in advance for the noise and kindly ask for an explanation of the rationale if possible, I might be misunderstanding things - kind of newbie to Micronaut.

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided

### Steps to Reproduce

I have a list of Integers:

`List<Integer> items = IntStream.range(0, 20).boxed().collect(Collectors.toList());`

I am slicing it and creating a page and a Pageable out it:

```java
Pageable pageable = Pageable.from(6, 3);

final List<T> splitItems = items.stream()
      .skip(pageable.getOffset())  // it correctly returns 18
      .limit(pageable.getSize())    // it correctly returns 3
      .collect(Collectors.toList());

// This will be my last page - the sixth, given I have three elements per page.
Page<Integer> page = Page.of(splitItems, pageable , items.size());
```

### Expected Behaviour

Now I want to get the offset of the previous pageable for the page so I go:

```
long previousOffset = page.previousPageable().getOffset();
```

I expected `15`.

### Actual Behaviour

The actual call returns `9`.

[Guess Time] It seems that the [code](https://github.com/micronaut-projects/micronaut-data/blob/master/data-model/src/main/java/io/micronaut/data/model/Pageable.java#L100) that calculates the previous pageable subtracts the `size` instead of what I would expect, that is `1`.

Contrasting that with `next()`, it seems different. I don't know if correct or not a this point :smile: 

### Environment Information

- `io.micronaut.data:micronaut-data-model:1.0.2`
