### ISSUE TITLE
Issue with bidirectional relationship

### ISSUE THREAD

**Issue by PiotrBaczkowski** [micronaut-projects/micronaut-data#760]
There is an issue with mapping bidirectional relationship

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

GET /categories

### Expected Behaviour
Successfully returned list of items

### Actual Behaviour
Returned error 

### Environment Information

Operating System: MacOs BigSur
Micronaut Version: 2.0.3
JDK Version: 11
Kotlin version 1.3.72

### Example Application
https://github.com/PiotrBaczkowski/micronautdataissue/tree/mapping-issue

**Comment by issmo** [comment]
This is most probably linked to the issue described in this comment https://github.com/micronaut-projects/micronaut-data/issues/669#issuecomment-723247789

**Comment by dstepanov** [comment]
This is duplicated of #669.
